### ISSUE TITLE
error C1189: #error :  "No Target Architecture"

### ISSUE THREAD

**Issue by M-youyou** [DMIunipg/AI-Gestures-Classifier#1]
When I run your code on my computer, I encounter the following errors:
 "error C1189: #error :  "No Target Architecture" ";
 "error C2065: “field”: undeclared identifier  ...\knn\knn.cpp	46	1	myo_Classifier_Test
 "error C2228: left of '.mRaw' must have class/struct/union"
 "error C2327: "kNN::mDataSet"not a type name, static, or enumerator"
 "error C3312: no callable 'begin' function found for type 'unknown-type' "
 .....
 Do you encounter those errors and how you fix them?

 Best wishes and I look forward to your reply.

**Comment by Gabriele91** [comment]
Thank you for report, sorry for the time to wait.
I merged the developer branch with master branch and I fixed some issues with new Android SDK/NDK. Try to compile the project again! And ASK to me if you have other issues.

**Comment by Gabriele91** [comment]
P.S. The Android projects "MyoClassifier" and "MyoClassifierUnofficialSdk" are deprecated, now I work on MyoClassifierUnofficialSdkParrot.

**Comment by M-youyou** [comment]
Thanks very much for your answer. It is very helpful, but I still have some question when I try to run "GesturesClassifierWorkSpace.sln" in folder “GesturesClassifierWorkSpace”.
The error is in file "kNN,cpp", and the error code is:
` //serach in data set`
 **`//"error C2065: “mDataSet”: undeclared identifier`  
` //error C2327: "kNN::mDataSet"not a type name, static, or enumerator`**
` for(auto& field:mDataSet)`               
`{`                                        
       **`//error C3312: no callable 'begin' function found for type 'unknown-type' `   
      ` //error C3312: no callable 'end' function found for type 'unknown-type' `** 
      `//compute distance`
       ` double rfdistance = 0.0;`
        `//select distance type`
        `switch (type)`
       ` {`
            `default:`
            `case EUCLIDE_DISTANCE:   rfdistance = distance(field.mRaw, row);  break;`   
            **`//error C2065: “field”: undeclared identifier`   
            `//error C2228: left of '.mRaw' must have class/struct/union`**
            `case MANHATTAN_DISTANCE: rfdistance = manhattan(field.mRaw, row);  break;`  
            **`//error C2065: “field”: undeclared identifier`   
           `//error C2228: left of '.mRaw' must have class/struct/union`**
            `case HAMMING_DISTANCE:   rfdistance = hamming(field.mRaw, row);  break;`    
            **`//error C2065: “field”: undeclared identifier`   
           `//error C2228: left of '.mRaw' must have class/struct/union`**
       ` }`
		`//not all selected`
		`if (rowAdded < selected.size())`
		`{`
			`for (auto& selectRow : selected)`
			`{`
				`if (!selectRow.mField)`
				`{`
					`selectRow.mDistance = rfdistance;`
					`selectRow.mField = &field;`
					`//get max`
					`if (!mostDistanceField || mostDistanceField->mDistance < rfdistance)`
					`{`
						`mostDistanceField = &selectRow;`
					`}`
					`//inc `
					`++rowAdded;`
					`//next`
					`break;`
				`}`
			`}`
		`}`
		`//all selected rows are occupied`
		`else `
		`{`
			`if (mostDistanceField->mDistance > rfdistance)`
			`{`
				`mostDistanceField->mDistance = rfdistance;`
				`mostDistanceField->mField = &field;`             
                                **` //"error C2065: “field”: undeclared identifier`**
				`//search most distance field`
				`for (auto& selectRow : selected)`
				`{`
					`//get max`
					`if (mostDistanceField->mDistance < rfdistance)`
					`{`
						`mostDistanceField = &selectRow;`
					`}`
				`}`
			`}`
		`}`
    `}`

My compiler environment is Microsoft Visual Studio Ultimate 2013 and my Platform Toolset is Visual Studio 2013(v120).
I have confused with this problem for a whole and I  look forward to your reply.

**Comment by M-youyou** [comment]
Thanks very much for your answer. It is very helpful, but I still have some questions when I try to run "GesturesClassifierWorkSpace.sln" in folder “GesturesClassifierWorkSpace”.
The error is in file "kNN,cpp", and the error code is:
//serach in data set
//"error C2065: “mDataSet”: undeclared identifier

//error C2327: "kNN::mDataSet"not a type name, static, or enumerator
for(auto& field:mDataSet)

{

//error C3312: no callable 'begin' function found for type 'unknown-type'

//error C3312: no callable 'end' function found for type 'unknown-type' 
//compute distance
double rfdistance = 0.0;
//select distance type
switch (type)
{
default:
case EUCLIDE_DISTANCE: rfdistance = distance(field.mRaw, row); break;

//error C2065: “field”: undeclared identifier

//error C2228: left of '.mRaw' must have class/struct/union
case MANHATTAN_DISTANCE: rfdistance = manhattan(field.mRaw, row); break;

//error C2065: “field”: undeclared identifier

//error C2228: left of '.mRaw' must have class/struct/union
case HAMMING_DISTANCE: rfdistance = hamming(field.mRaw, row); break;

//error C2065: “field”: undeclared identifier

//error C2228: left of '.mRaw' must have class/struct/union
}
//not all selected
if (rowAdded < selected.size())
{
for (auto& selectRow : selected)
{
if (!selectRow.mField)
{
selectRow.mDistance = rfdistance;
selectRow.mField = &field;
//get max
if (!mostDistanceField || mostDistanceField->mDistance < rfdistance)
{
mostDistanceField = &selectRow;
}
//inc
++rowAdded;
//next
break;
}
}
}
//all selected rows are occupied
else
{
if (mostDistanceField->mDistance > rfdistance)
{
mostDistanceField->mDistance = rfdistance;
mostDistanceField->mField = &field;

//"error C2065: “field”: undeclared identifier
//search most distance field
for (auto& selectRow : selected)
{
//get max
if (mostDistanceField->mDistance < rfdistance)
{
mostDistanceField = &selectRow;
}
}
}
}
}

My compiler environment is Microsoft Visual Studio Ultimate 2013 and my Platform Toolset is Visual Studio 2013(v120).
I have confused with this problem for a whole and I look forward to your reply.

**Comment by M-youyou** [comment]
Thanks very much for your answer. It is very helpful, but I still have some questions when I try to run "GesturesClassifierWorkSpace.sln" in folder “GesturesClassifierWorkSpace”.
The error is in file "kNN,cpp", and the error code is:
`//serach in data set `
**`//error C2065: “mDataSet”: undeclared identifier //error C2327: "kNN::mDataSet"not a type name, static, or enumerator`**
`for(auto& field:mDataSet)`
`{`
**`//error C3312: no callable 'begin' function found for type 'unknown-type'
//error C3312: no callable 'end' function found for type 'unknown-type' `**
`//compute distance`
`double rfdistance = 0.0;`
`//select distance type`
`switch (type)`
`{`
`default:`
`case EUCLIDE_DISTANCE: rfdistance = distance(field.mRaw, row); break;`
**`//error C2065: “field”: undeclared identifier //error C2228: left of '.mRaw' must have class/struct/union`**
`case MANHATTAN_DISTANCE: rfdistance = manhattan(field.mRaw, row); break;`
**`//error C2065: “field”: undeclared identifier
//error C2228: left of '.mRaw' must have class/struct/union`**
`case HAMMING_DISTANCE: rfdistance = hamming(field.mRaw, row); break;`
**`//error C2065: “field”: undeclared identifier
//error C2228: left of '.mRaw' must have class/struct/union`**
`}`
`//not all selected`
`if (rowAdded < selected.size())`
`{`
`for (auto& selectRow : selected)`
`{`
`if (!selectRow.mField)`
`{`
`selectRow.mDistance = rfdistance;`
`selectRow.mField = &field;`
`//get max`
`if (!mostDistanceField || mostDistanceField->mDistance < rfdistance)`
`{`
`mostDistanceField = &selectRow;`
`}`
`//inc`
`++rowAdded;`
`//next`
`break;`
`}`
`}`
`}`
`//all selected rows are occupied`
`else`
`{`
`if (mostDistanceField->mDistance > rfdistance)`
`{`
`mostDistanceField->mDistance = rfdistance;`
`mostDistanceField->mField = &field;`
**`//"error C2065: “field”: undeclared identifier`**
`//search most distance field`
`for (auto& selectRow : selected)`
`{`
`//get max`
`if (mostDistanceField->mDistance < rfdistance)`
`{`
`mostDistanceField = &selectRow;`
`}`
`}`
`}`
`}`
`}`

My compiler environment is Microsoft Visual Studio Ultimate 2013 and my Platform Toolset is Visual Studio 2013(v120).
I have confused with this problem for a whole and I look forward to your reply.

**Comment by Gabriele91** [comment]
I'm working with VS2015 (and v140) because it has a better support to C++11 and a better type deduction system.
But anyway I fixed the issue in the [last commit](https://github.com/DMIunipg/AI-Gestures-Classifier/commit/45b738f97f0150a7a99bea2345cdfe1e61a3f344)!! VS2013&v120 I have got a success to compile.
Update your local repository and try to compile again!

This is the most significant change:
`#if defined(_MSC_VER) && (_MSC_VER <= 1800)`
`    for (DataSetReader::Rows::const_iterator`
`         itField  = this->mDataSet.cbegin(); `
`         itField != this->mDataSet.cend();`
`         ++itField)`
`    {`
 `       auto& field = *itField;`
`#else`
`     for (auto& field : mDataSet)`
`     {`
`#endi`
